### ISSUE TITLE
Need to display prices with trailing zeros

### ISSUE THREAD

**Issue by katiekeel** [katieshermer/black_thursday#1]
Need to modify :unit_price input in Item initialize so that it will still display 14.50 if price is transformed from a string to an integer.

**Comment by thedanielvogelsang** [comment]
fixed it I think, but I'll wait until tomorrow to commit/push

**Comment by thedanielvogelsang** [comment]
also put the .to_s method in the unit_price, in order to account for possible fixnum entries, though maybe this is unnecessary?
